# Generated by Django 2.0 on 2017-12-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('publish_date', models.DateTimeField()),
                ('book_category', models.CharField(blank=True, default='', max_length=200)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
